import urllib.request
import urllib.parse
import re
import json

# Define the exhaustive catalog
perfumes = [
    # ---- MALE ----
    # Designers
    { "id": "p1", "name": "Dior Sauvage Elixir", "brand": "Dior", "gender": "male", "price_range": "Niche/Luxury ($150+)", "price_category": "niche", "notes": ["Grapefruit", "Cinnamon", "Nutmeg", "Lavender", "Sandalwood", "Patchouli"], "vibe": ["Spicy & Bold", "Woody & Earthy"], "occasion": ["Date Night/Romantic", "Signature/Daily Wear"], "power": ["Longevity", "Projection/Sillage"], "context": ["Cold Weather", "Night"], "psychology": ["Compliment Factor", "Brand & Presentation"], "wearing_time": "12+ hours", "season": "Fall/Winter", "smell_type": "Warm Spicy / Woody", "performance": "Beast Mode", "longevity": "Eternal", "description": "An extraordinarily concentrated fragrance steeped in the emblematic freshness of Sauvage." },
    { "id": "p2", "name": "Bleu de Chanel Parfum", "brand": "Chanel", "gender": "male", "price_range": "Designer ($100 - $150)", "price_category": "designer", "notes": ["Lemon Zest", "Mint", "Pineapple", "Geranium", "Sandalwood", "Cedar"], "vibe": ["Fresh & Clean", "Woody & Earthy"], "occasion": ["Office/Professional", "Signature/Daily Wear"], "power": ["Versatility"], "context": ["All Weather", "Day", "Night"], "psychology": ["Compliment Factor", "Brand & Presentation"], "wearing_time": "8-10 hours", "season": "All Seasons", "smell_type": "Citrus Woods", "performance": "Moderate/Strong", "longevity": "Long Lasting", "description": "Majestic and mysterious, expressing intensity and refinement." },
    { "id": "p3", "name": "YSL Y Eau de Parfum", "brand": "Yves Saint Laurent", "gender": "male", "price_range": "Designer ($100 - $150)", "price_category": "designer", "notes": ["Apple", "Ginger", "Bergamot", "Sage", "Juniper", "Amberwood"], "vibe": ["Fresh & Clean", "Sweet & Gourmand"], "occasion": ["Office/Professional", "Gym/Sport", "Signature/Daily Wear"], "power": ["Projection/Sillage", "Versatility"], "context": ["All Weather", "Day"], "psychology": ["Compliment Factor", "Brand & Presentation"], "wearing_time": "10 hours", "season": "All Seasons", "smell_type": "Aromatic Fougere", "performance": "Strong", "longevity": "Long Lasting", "description": "A versatile everyday masterpiece bursting with fresh green apple and sage." },
    { "id": "p4", "name": "Acqua di Gio Profumo", "brand": "Giorgio Armani", "gender": "male", "price_range": "Designer ($100 - $150)", "price_category": "designer", "notes": ["Sea Notes", "Bergamot", "Rosemary", "Sage", "Incense", "Patchouli"], "vibe": ["Fresh & Clean", "Woody & Earthy"], "occasion": ["Office/Professional", "Signature/Daily Wear", "Date Night/Romantic"], "power": ["Versatility", "Longevity"], "context": ["Hot Weather", "Day"], "psychology": ["Compliment Factor", "Brand & Presentation"], "wearing_time": "8 hours", "season": "Spring/Summer", "smell_type": "Aromatic Aquatic", "performance": "Moderate", "longevity": "Long Lasting", "description": "The deep, dark, and incense-heavy flanker of a worldwide aquatic classic." },
    { "id": "p5", "name": "Versace Eros", "brand": "Versace", "gender": "male", "price_range": "Designer ($100 - $150)", "price_category": "designer", "notes": ["Mint", "Green Apple", "Lemon", "Tonka Bean", "Ambroxan", "Vanilla"], "vibe": ["Sweet & Gourmand", "Fresh & Clean"], "occasion": ["Date Night/Romantic"], "power": ["Projection/Sillage", "Longevity"], "context": ["Cold Weather", "Night"], "psychology": ["Compliment Factor"], "wearing_time": "12 hours", "season": "Fall/Winter", "smell_type": "Aromatic Fougere", "performance": "Beast Mode", "longevity": "Eternal", "description": "The ultimate clubbing fragrance radiating youth, extreme sweetness, and mint." },
    { "id": "p6", "name": "Terre d'Hermes", "brand": "Hermes", "gender": "male", "price_range": "Designer ($100 - $150)", "price_category": "designer", "notes": ["Orange", "Grapefruit", "Pepper", "Pelargonium", "Vetiver", "Cedar"], "vibe": ["Woody & Earthy", "Spicy & Bold"], "occasion": ["Office/Professional", "Signature/Daily Wear"], "power": ["Versatility"], "context": ["All Weather", "Day"], "psychology": ["Brand & Presentation"], "wearing_time": "8 hours", "season": "Spring/Fall", "smell_type": "Woody Spicy", "performance": "Moderate", "longevity": "Moderate", "description": "A grounded, mature scent emphasizing bitter orange, flint, and dirty vetiver." },
    { "id": "p7", "name": "Prada L'Homme", "brand": "Prada", "gender": "male", "price_range": "Designer ($100 - $150)", "price_category": "designer", "notes": ["Neroli", "Pepper", "Iris", "Amber", "Violet", "Cedar"], "vibe": ["Floral", "Fresh & Clean"], "occasion": ["Office/Professional", "Signature/Daily Wear"], "power": ["Versatility"], "context": ["All Weather", "Day"], "psychology": ["Compliment Factor", "Brand & Presentation"], "wearing_time": "8 hours", "season": "Spring/Summer", "smell_type": "Woody Chypre", "performance": "Moderate", "longevity": "Moderate", "description": "The king of office fragrances. Exceptionally clean, soapy iris." },
    { "id": "p8", "name": "Viktor&Rolf Spicebomb Extreme", "brand": "Viktor&Rolf", "gender": "male", "price_range": "Designer ($100 - $150)", "price_category": "designer", "notes": ["Caraway", "Lavender", "Black Pepper", "Tobacco", "Vanilla"], "vibe": ["Spicy & Bold", "Sweet & Gourmand"], "occasion": ["Date Night/Romantic"], "power": ["Longevity", "Projection/Sillage"], "context": ["Cold Weather", "Night"], "psychology": ["Compliment Factor"], "wearing_time": "12+ hours", "season": "Winter", "smell_type": "Oriental Spicy", "performance": "Beast Mode", "longevity": "Eternal", "description": "An explosion of heat with black pepper, cinnamon, and comforting vanilla." },
    
    # Niche Male
    { "id": "p9", "name": "Creed Aventus", "brand": "Creed", "gender": "male", "price_range": "Niche/Luxury ($300+)", "price_category": "niche", "notes": ["Pineapple", "Bergamot", "Birch", "Patchouli", "Musk", "Oakmoss"], "vibe": ["Fresh & Clean", "Woody & Earthy"], "occasion": ["Office/Professional", "Signature/Daily Wear", "Date Night/Romantic"], "power": ["Versatility", "Projection/Sillage"], "context": ["All Weather", "Day", "Night"], "psychology": ["Compliment Factor", "Brand & Presentation"], "wearing_time": "8-10 hours", "season": "All Seasons", "smell_type": "Fruity Chypre", "performance": "Strong", "longevity": "Long Lasting", "description": "The King of Men's Fragrances. Bright pineapple seamlessly blended with dark smoky woods." },
    { "id": "p10", "name": "Parfums de Marly Layton", "brand": "Parfums de Marly", "gender": "male", "price_range": "Niche/Luxury ($200+)", "price_category": "niche", "notes": ["Apple", "Lavender", "Bergamot", "Vanilla", "Cardamom", "Sandalwood"], "vibe": ["Sweet & Gourmand", "Spicy & Bold"], "occasion": ["Date Night/Romantic", "Signature/Daily Wear"], "power": ["Longevity", "Projection/Sillage"], "context": ["Cold Weather", "Night"], "psychology": ["Compliment Factor", "Brand & Presentation"], "wearing_time": "12 hours", "season": "Fall/Winter", "smell_type": "Oriental Floral", "performance": "Strong", "longevity": "Long Lasting", "description": "A seductive blend of apple, vanilla, and spices crafted for nobility." },
    { "id": "p11", "name": "Roja Elysium", "brand": "Roja Parfums", "gender": "male", "price_range": "Niche/Luxury ($300+)", "price_category": "niche", "notes": ["Grapefruit", "Lemon", "Galbanum", "Vetiver", "Ambergris"], "vibe": ["Fresh & Clean"], "occasion": ["Office/Professional", "Signature/Daily Wear"], "power": ["Versatility"], "context": ["Hot Weather", "Day"], "psychology": ["Brand & Presentation"], "wearing_time": "6 hours", "season": "Summer", "smell_type": "Aromatic Fougere", "performance": "Moderate", "longevity": "Moderate", "description": "Ultra-luxury citrus overload that smells like pure wealth in the sunshine." },
    
    # Budget Male
    { "id": "p12", "name": "Lattafa Asad", "brand": "Lattafa", "gender": "male", "price_range": "Budget (< $50)", "price_category": "budget", "notes": ["Black Pepper", "Pineapple", "Tobacco", "Coffee", "Patchouli", "Vanilla"], "vibe": ["Spicy & Bold"], "occasion": ["Date Night/Romantic", "Signature/Daily Wear"], "power": ["Longevity", "Projection/Sillage"], "context": ["Cold Weather", "Night"], "psychology": ["Price-to-Value Ratio", "Compliment Factor"], "wearing_time": "8-10 hours", "season": "Fall/Winter", "smell_type": "Spicy Amber", "performance": "Strong", "longevity": "Long Lasting", "description": "An exceptional clone of Sauvage Elixir offering unbeatable value." },
    { "id": "p13", "name": "Nautica Voyage", "brand": "Nautica", "gender": "male", "price_range": "Budget (< $50)", "price_category": "budget", "notes": ["Apple", "Green Leaves", "Lotus", "Musk", "Cedar"], "vibe": ["Fresh & Clean"], "occasion": ["Gym/Sport", "Office/Professional", "Signature/Daily Wear"], "power": ["Versatility"], "context": ["Hot Weather", "Day"], "psychology": ["Price-to-Value Ratio"], "wearing_time": "6 hours", "season": "Summer", "smell_type": "Aquatic Fresh", "performance": "Moderate", "longevity": "Moderate", "description": "A fresh, salty sea breeze that carries coastal herbs. Unbeatable cheap freshie." },
    { "id": "p14", "name": "Armaf Club de Nuit Intense Man", "brand": "Armaf", "gender": "male", "price_range": "Budget (< $50)", "price_category": "budget", "notes": ["Lemon", "Pineapple", "Birch", "Jasmine", "Musk", "Ambergris"], "vibe": ["Fresh & Clean", "Woody & Earthy"], "occasion": ["Signature/Daily Wear", "Date Night/Romantic"], "power": ["Longevity", "Projection/Sillage"], "context": ["All Weather", "Day", "Night"], "psychology": ["Compliment Factor", "Price-to-Value Ratio"], "wearing_time": "12 hours", "season": "All Seasons", "smell_type": "Woody Spicy", "performance": "Beast Mode", "longevity": "Eternal", "description": "The infamous powerhouse clone. Pungent opening but a dry down that fools Aventus lovers." },
    { "id": "p15", "name": "Afnan 9pm", "brand": "Afnan", "gender": "male", "price_range": "Budget (< $50)", "price_category": "budget", "notes": ["Apple", "Cinnamon", "Lavender", "Vanilla", "Tonka Bean"], "vibe": ["Sweet & Gourmand", "Spicy & Bold"], "occasion": ["Date Night/Romantic"], "power": ["Longevity", "Projection/Sillage"], "context": ["Cold Weather", "Night"], "psychology": ["Price-to-Value Ratio", "Compliment Factor"], "wearing_time": "10 hours", "season": "Fall/Winter", "smell_type": "Vanilla Spicy", "performance": "Strong", "longevity": "Long Lasting", "description": "A stunning alternative to Ultramale. Perfect sweet, loud clubbing juice." },

    # ---- FEMALE ----
    # Designers
    { "id": "p16", "name": "YSL Libre Intense", "brand": "Yves Saint Laurent", "gender": "female", "price_range": "Designer ($100 - $150)", "price_category": "designer", "notes": ["Lavender", "Orchid", "Orange Blossom", "Vanilla", "Tonka Bean"], "vibe": ["Floral", "Sweet & Gourmand"], "occasion": ["Date Night/Romantic", "Signature/Daily Wear"], "power": ["Longevity", "Projection/Sillage"], "context": ["Cold Weather", "Night"], "psychology": ["Compliment Factor", "Brand & Presentation"], "wearing_time": "10-12 hours", "season": "Fall/Winter", "smell_type": "Warm Floral Vanilla", "performance": "Beast Mode", "longevity": "Eternal", "description": "The fragrance of freedom, dialed up. Sensual and fiery." },
    { "id": "p17", "name": "Carolina Herrera Good Girl", "brand": "Carolina Herrera", "gender": "female", "price_range": "Designer ($100 - $150)", "price_category": "designer", "notes": ["Almond", "Coffee", "Jasmine", "Tuberose", "Tonka Bean", "Cacao"], "vibe": ["Sweet & Gourmand", "Floral", "Spicy & Bold"], "occasion": ["Date Night/Romantic"], "power": ["Projection/Sillage", "Longevity"], "context": ["Cold Weather", "Night"], "psychology": ["Compliment Factor", "Brand & Presentation"], "wearing_time": "8-10 hours", "season": "Fall/Winter", "smell_type": "Sweet White Floral", "performance": "Strong", "longevity": "Long Lasting", "description": "A daring fragrance in an iconic stiletto bottle, expressing duality." },
    { "id": "p18", "name": "YSL Black Opium", "brand": "Yves Saint Laurent", "gender": "female", "price_range": "Designer ($100 - $150)", "price_category": "designer", "notes": ["Pear", "Pink Pepper", "Coffee", "Jasmine", "Vanilla", "Patchouli"], "vibe": ["Sweet & Gourmand", "Spicy & Bold"], "occasion": ["Date Night/Romantic", "Signature/Daily Wear"], "power": ["Longevity"], "context": ["Cold Weather", "Night"], "psychology": ["Compliment Factor"], "wearing_time": "8 hours", "season": "Winter", "smell_type": "Vanilla Coffee", "performance": "Moderate", "longevity": "Moderate", "description": "A highly addictive feminine fragrance boasting rich coffee and sweet vanilla." },
    { "id": "p19", "name": "Chanel Coco Mademoiselle", "brand": "Chanel", "gender": "female", "price_range": "Designer ($100 - $150)", "price_category": "designer", "notes": ["Orange", "Mandarin", "Turkish Rose", "Jasmine", "Patchouli", "Vetiver"], "vibe": ["Floral", "Fresh & Clean"], "occasion": ["Office/Professional", "Signature/Daily Wear"], "power": ["Versatility", "Longevity"], "context": ["All Weather", "Day"], "psychology": ["Brand & Presentation", "Compliment Factor"], "wearing_time": "10 hours", "season": "All Seasons", "smell_type": "Oriental Floral", "performance": "Strong", "longevity": "Long Lasting", "description": "Irresistibly sexy, irrepressibly spirited. A sparkling oriental fragrance." },
    { "id": "p20", "name": "Lancome La Vie Est Belle", "brand": "Lancome", "gender": "female", "price_range": "Designer ($100 - $150)", "price_category": "designer", "notes": ["Blackcurrant", "Pear", "Iris", "Jasmine", "Praline", "Vanilla"], "vibe": ["Sweet & Gourmand", "Floral"], "occasion": ["Signature/Daily Wear", "Date Night/Romantic"], "power": ["Projection/Sillage", "Longevity"], "context": ["Cold Weather", "Day"], "psychology": ["Compliment Factor"], "wearing_time": "12 hours", "season": "Fall/Winter", "smell_type": "Floral Fruity Gourmand", "performance": "Beast Mode", "longevity": "Eternal", "description": "A universal declaration to the beauty of life, spun with sweet praline and iris." },
    { "id": "p21", "name": "Dior Miss Dior Eau de Parfum", "brand": "Dior", "gender": "female", "price_range": "Designer ($100 - $150)", "price_category": "designer", "notes": ["Iris", "Peony", "Rose", "Apricot", "Tonka Bean", "Musk"], "vibe": ["Floral", "Sweet & Gourmand"], "occasion": ["Date Night/Romantic", "Signature/Daily Wear"], "power": ["Versatility"], "context": ["All Weather", "Day"], "psychology": ["Brand & Presentation"], "wearing_time": "8 hours", "season": "Spring", "smell_type": "Amber Floral", "performance": "Moderate", "longevity": "Moderate", "description": "Like a bouquet of colorful flowers wrapped in powdery softness." },

    # Niche Female
    { "id": "p22", "name": "Parfums de Marly Delina", "brand": "Parfums de Marly", "gender": "female", "price_range": "Niche/Luxury ($300+)", "price_category": "niche", "notes": ["Litchi", "Rhubarb", "Bergamot", "Turkish Rose", "Peony", "Vanilla", "Musk"], "vibe": ["Floral", "Fresh & Clean", "Sweet & Gourmand"], "occasion": ["Date Night/Romantic", "Signature/Daily Wear"], "power": ["Longevity", "Projection/Sillage", "Versatility"], "context": ["All Weather", "Day"], "psychology": ["Compliment Factor", "Brand & Presentation"], "wearing_time": "12+ hours", "season": "Spring/Summer", "smell_type": "Floral Fruity", "performance": "Strong", "longevity": "Long Lasting", "description": "A highly nuanced fragrance which is both sweet and sensual. The ultimate modern rose." },
    { "id": "p23", "name": "Kilian Love Don't Be Shy", "brand": "Kilian", "gender": "female", "price_range": "Niche/Luxury ($250+)", "price_category": "niche", "notes": ["Neroli", "Pink Pepper", "Orange Blossom", "Marshmallow", "Vanilla", "Caramel"], "vibe": ["Sweet & Gourmand", "Floral"], "occasion": ["Date Night/Romantic"], "power": ["Longevity", "Projection/Sillage"], "context": ["Cold Weather", "Night"], "psychology": ["Compliment Factor", "Brand & Presentation"], "wearing_time": "10 hours", "season": "Fall/Winter", "smell_type": "Amber Floral", "performance": "Strong", "longevity": "Long Lasting", "description": "Exhilarating, unforgettable orange blossom wrapped in sweet, lush marshmallow." },
    { "id": "p24", "name": "Maison Francis Kurkdjian Grand Soir", "brand": "Maison Francis Kurkdjian", "gender": "female", "price_range": "Niche/Luxury ($250+)", "price_category": "niche", "notes": ["Labdanum", "Benzoin", "Tonka Bean", "Vanilla", "Amber"], "vibe": ["Sweet & Gourmand", "Spicy & Bold"], "occasion": ["Date Night/Romantic"], "power": ["Longevity", "Projection/Sillage"], "context": ["Cold Weather", "Night"], "psychology": ["Compliment Factor", "Brand & Presentation"], "wearing_time": "14 hours", "season": "Winter", "smell_type": "Amber", "performance": "Beast Mode", "longevity": "Eternal", "description": "Invites you to dress up and walk the bridges of Paris. A regal amber masterpiece." },

    # Budget Female
    { "id": "p25", "name": "Ariana Grande Cloud", "brand": "Ariana Grande", "gender": "female", "price_range": "Budget (< $50)", "price_category": "budget", "notes": ["Lavender", "Pear", "Coconut", "Praline", "Vanilla Orchid", "Musk"], "vibe": ["Sweet & Gourmand"], "occasion": ["Signature/Daily Wear", "Office/Professional"], "power": ["Versatility"], "context": ["All Weather", "Day"], "psychology": ["Price-to-Value Ratio", "Compliment Factor"], "wearing_time": "6-8 hours", "season": "All Seasons", "smell_type": "Sweet Airy Coconut", "performance": "Moderate/Strong", "longevity": "Long Lasting", "description": "An uplifting, sweet, and comforting scent often compared to an airy BR540." },
    { "id": "p26", "name": "Lattafa Yara", "brand": "Lattafa", "gender": "female", "price_range": "Budget (< $50)", "price_category": "budget", "notes": ["Heliotrope", "Orchid", "Tangerine", "Gourmand Accord", "Vanilla", "Musk"], "vibe": ["Sweet & Gourmand", "Floral"], "occasion": ["Signature/Daily Wear", "Date Night/Romantic"], "power": ["Versatility"], "context": ["All Weather", "Day"], "psychology": ["Price-to-Value Ratio", "Compliment Factor"], "wearing_time": "8 hours", "season": "Spring/Summer", "smell_type": "Fruity Gourmand", "performance": "Moderate", "longevity": "Moderate", "description": "A viral sensation conveying a creamy strawberry milkshake vibe." },
    { "id": "p27", "name": "Armaf Club de Nuit Woman", "brand": "Armaf", "gender": "female", "price_range": "Budget (< $50)", "price_category": "budget", "notes": ["Orange", "Grapefruit", "Peach", "Rose", "Jasmine", "Patchouli"], "vibe": ["Floral", "Fresh & Clean"], "occasion": ["Office/Professional", "Signature/Daily Wear"], "power": ["Longevity", "Versatility"], "context": ["All Weather", "Day"], "psychology": ["Price-to-Value Ratio"], "wearing_time": "10 hours", "season": "All Seasons", "smell_type": "Floral Fruity", "performance": "Strong", "longevity": "Long Lasting", "description": "An incredibly accurate interpretation of Coco Mademoiselle for a fraction of the cost." },

    # ---- UNISEX ----
    # Designers / Prestigious Collections
    { "id": "p28", "name": "Tom Ford Black Orchid", "brand": "Tom Ford", "gender": "unisex", "price_range": "Designer ($100 - $150)", "price_category": "designer", "notes": ["Truffle", "Gardenia", "Blackcurrant", "Orchid", "Spices", "Dark Chocolate"], "vibe": ["Woody & Earthy", "Floral", "Spicy & Bold"], "occasion": ["Date Night/Romantic"], "power": ["Longevity", "Projection/Sillage"], "context": ["Cold Weather", "Night"], "psychology": ["Brand & Presentation"], "wearing_time": "12+ hours", "season": "Fall/Winter", "smell_type": "Dark Earthy Floral", "performance": "Beast Mode", "longevity": "Eternal", "description": "Sensual and dark accords with an alluring potion of orchids and earth." },
    { "id": "p29", "name": "Maison Margiela By The Fireplace", "brand": "Maison Margiela", "gender": "unisex", "price_range": "Designer ($100 - $150)", "price_category": "designer", "notes": ["Cloves", "Pink Pepper", "Chestnut", "Guaiac Wood", "Vanilla", "Cashmeran"], "vibe": ["Woody & Earthy", "Sweet & Gourmand"], "occasion": ["Signature/Daily Wear"], "power": ["Longevity"], "context": ["Cold Weather", "Night"], "psychology": ["Compliment Factor"], "wearing_time": "8 hours", "season": "Winter", "smell_type": "Woody Fragrance", "performance": "Moderate", "longevity": "Moderate", "description": "Evokes the memory of wood crackling gracefully in the winter hearth." },
    { "id": "p30", "name": "Maison Margiela Jazz Club", "brand": "Maison Margiela", "gender": "unisex", "price_range": "Designer ($100 - $150)", "price_category": "designer", "notes": ["Pink Pepper", "Lemon", "Rum", "Clary Sage", "Tobacco Leaf", "Vanilla"], "vibe": ["Spicy & Bold", "Sweet & Gourmand"], "occasion": ["Date Night/Romantic"], "power": ["Versatility"], "context": ["Cold Weather", "Night"], "psychology": ["Compliment Factor"], "wearing_time": "8 hours", "season": "Fall/Winter", "smell_type": "Leather", "performance": "Moderate", "longevity": "Moderate", "description": "The balmy base scent of cigars and exhilarating rum." },

    # Niche Unisex
    { "id": "p31", "name": "Baccarat Rouge 540 Extrait", "brand": "Maison Francis Kurkdjian", "gender": "unisex", "price_range": "Niche/Luxury ($300+)", "price_category": "niche", "notes": ["Bitter Almond", "Saffron", "Egyptian Jasmine", "Cedar", "Ambergris", "Musk"], "vibe": ["Sweet & Gourmand", "Woody & Earthy"], "occasion": ["Date Night/Romantic", "Signature/Daily Wear"], "power": ["Longevity", "Projection/Sillage"], "context": ["All Weather", "Night", "Day"], "psychology": ["Compliment Factor", "Brand & Presentation"], "wearing_time": "14+ hours", "season": "Fall/Winter/Spring", "smell_type": "Woody Amber Floral", "performance": "Nuclear", "longevity": "Eternal", "description": "An incandescent and radiant aura amplifying amber woody floral elements." },
    { "id": "p32", "name": "Le Labo Santal 33", "brand": "Le Labo", "gender": "unisex", "price_range": "Niche/Luxury ($250+)", "price_category": "niche", "notes": ["Sandalwood", "Leather", "Papyrus", "Virginia Cedar", "Violet", "Cardamom"], "vibe": ["Woody & Earthy", "Spicy & Bold"], "occasion": ["Office/Professional", "Signature/Daily Wear"], "power": ["Longevity", "Projection/Sillage", "Versatility"], "context": ["All Weather", "Day"], "psychology": ["Brand & Presentation", "Compliment Factor"], "wearing_time": "12 hours", "season": "All Seasons", "smell_type": "Woody Aromatic", "performance": "Strong", "longevity": "Eternal", "description": "The quintessential scent of the modern creative scene. Dry cedar and leather." },
    { "id": "p33", "name": "Tom Ford Lost Cherry", "brand": "Tom Ford", "gender": "unisex", "price_range": "Niche/Luxury ($300+)", "price_category": "niche", "notes": ["Sour Cherry", "Bitter Almond", "Plum", "Turkish Rose", "Vanilla", "Tonka Bean"], "vibe": ["Sweet & Gourmand", "Floral"], "occasion": ["Date Night/Romantic"], "power": ["Projection/Sillage"], "context": ["Cold Weather", "Night"], "psychology": ["Brand & Presentation"], "wearing_time": "6-8 hours", "season": "Fall/Winter", "smell_type": "Amber Floral", "performance": "Moderate", "longevity": "Moderate", "description": "A full-bodied journey into the once-forbidden; a candy-like gleam on the outside." },
    { "id": "p34", "name": "Kilian Angels' Share", "brand": "Kilian", "gender": "unisex", "price_range": "Niche/Luxury ($200+)", "price_category": "niche", "notes": ["Cognac", "Cinnamon", "Tonka Bean", "Oak", "Praline", "Vanilla"], "vibe": ["Sweet & Gourmand", "Spicy & Bold"], "occasion": ["Date Night/Romantic"], "power": ["Longevity", "Projection/Sillage"], "context": ["Cold Weather", "Night"], "psychology": ["Compliment Factor", "Brand & Presentation"], "wearing_time": "12 hours", "season": "Winter", "smell_type": "Amber Vanilla", "performance": "Strong", "longevity": "Long Lasting", "description": "The essence of cognac derived from the liquor to give an exquisite caramel color." },
    { "id": "p35", "name": "Xerjoff Naxos", "brand": "Xerjoff", "gender": "unisex", "price_range": "Niche/Luxury ($200+)", "price_category": "niche", "notes": ["Lavender", "Bergamot", "Honey", "Cinnamon", "Tobacco", "Tonka Bean"], "vibe": ["Sweet & Gourmand", "Spicy & Bold"], "occasion": ["Date Night/Romantic", "Signature/Daily Wear"], "power": ["Longevity", "Projection/Sillage"], "context": ["Cold Weather", "Day"], "psychology": ["Compliment Factor", "Brand & Presentation"], "wearing_time": "14 hours", "season": "Fall/Winter", "smell_type": "Aromatic Spicy", "performance": "Nuclear", "longevity": "Eternal", "description": "A tribute to the grandeur of Sicily, swirling with sweet honey and robust tobacco." },

    # Budget Unisex
    { "id": "p36", "name": "Lattafa Khamrah", "brand": "Lattafa", "gender": "unisex", "price_range": "Budget (< $50)", "price_category": "budget", "notes": ["Cinnamon", "Nutmeg", "Praline", "Dates", "Vanilla", "Myrrh"], "vibe": ["Sweet & Gourmand", "Spicy & Bold"], "occasion": ["Date Night/Romantic"], "power": ["Longevity", "Projection/Sillage"], "context": ["Cold Weather", "Night"], "psychology": ["Price-to-Value Ratio", "Compliment Factor"], "wearing_time": "12 hours", "season": "Winter", "smell_type": "Sweet Oriental", "performance": "Nuclear", "longevity": "Eternal", "description": "A boozy, sweet, and sticky dates-focused powerhouse cloned vaguely from Angels' Share." }
]

headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36'}

for p in perfumes:
    query = f"{p['name']} {p['brand']} perfume bottle isolate white background"
    url = f"https://www.bing.com/images/search?q={urllib.parse.quote(query)}"
    req = urllib.request.Request(url, headers=headers)
    img_url = ""
    try:
        html = urllib.request.urlopen(req).read().decode('utf-8')
        match = re.search(r'murl&quot;:&quot;(http[^&]+(?:jpg|png|webp))&quot;', html)
        if match:
            img_url = match.group(1)
            print(f"Found image for {p['name']}: {img_url}")
        else:
            # fallback pattern
            img_url = f"https://via.placeholder.com/400x500/111/9d4edd?text={urllib.parse.quote(p['name'])}"
            print(f"No match for {p['name']}")
    except Exception as e:
        img_url = f"https://via.placeholder.com/400x500/111/9d4edd?text={urllib.parse.quote(p['name'])}"
        print(f"Error for {p['name']}: {e}")
    
    p["aesthetic_image"] = img_url

# Now generate the javascript file
js_content = "export const PERFUME_DATABASE = " + json.dumps(perfumes, indent=2) + ";\n\n"

js_content += """
export const VIBES = [
  'Fresh & Clean',
  'Spicy & Bold',
  'Woody & Earthy',
  'Sweet & Gourmand',
  'Floral'
];

export const OCCASIONS = [
  'Office/Professional',
  'Date Night/Romantic',
  'Gym/Sport',
  'Signature/Daily Wear'
];

export const POWERS = [
  'Longevity',
  'Projection/Sillage',
  'Versatility'
];

export const CONTEXTS = [
  'Cold Weather', 'Hot Weather', 'All Weather', 'Day', 'Night'
];

export const PSYCHOLOGIES = [
  'Compliment Factor', 'Brand & Presentation', 'Price-to-Value Ratio'
];
"""

with open("src/data/perfumeDatabase.js", "w", encoding="utf-8") as f:
    f.write(js_content)

print("\nDatabase file generated successfully!")
